<a href="https://colab.research.google.com/github/eyka0209akssjjs0209/01-array/blob/main/latihan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as bakso


In [14]:

jumlah=int(input("jumlah mahasiswa:"))
i=1
for i in range(jumlah):
    nm=input(f"nama mahasiswa ke- {i}:")
    ni=input(f"nilai mahasiswa ke- {i}:")
i=+1

jumlah mahasiswa:2
nama mahasiswa ke- 0:dd
nilai mahasiswa ke- 0:ddd
nama mahasiswa ke- 1:ddd
nilai mahasiswa ke- 1:ddd


array satu dimensi

[20 10 30 40 50]


menampilkan data dari index tertentu

In [ ]:
wow=dimensi1[0]
print(wow)

20


rata-rata, nilai terkecil, terbesar dari array tsb.

In [ ]:
kecil=bakso.min(dimensi1)
besar=bakso.max(dimensi1)
rata2=bakso.mean(dimensi1)
print("nilai tercilik:", kecil)
print("nilai tERBESar:", besar)
print("nilai rata-rata:", rata2)

nilai tercilik: 10
nilai tERBESar: 50
nilai rata-rata: 30.0


arraY 2 dimensi

In [ ]:
dimensi2= bakso.array([[1,3,5,6],
 [2,9,7,10]])

In [ ]:
print(dimensi2)
hmmm= dimensi2[0,2]
print(hmmm)

[[ 1  3  5  6]
 [ 2  9  7 10]]
5


array 3 dimensi

In [ ]:
dimensi3= bakso.array([
    [[0,2,3],
     [4,5,6],
     [7,8,9]],
     [[10,12,13],
     [14,15,16],
     [17,18,19]]

])

In [ ]:
ahoy=dimensi3[1,1,2]
print(ahoy)

16
